export enum RuleId {
  DraftRoundSetupDrawCards = 1,
  DraftRoundPhaseCardSelection,
  DraftRoundPhaseTeamExchange,
  DraftRoundPhaseTeamCreation,
  DraftRoundPhaseBusDispatch,
  DraftRoundPhaseTeamReveal,
  DraftRoundPhaseMatchScore,
  DraftRoundPhaseMatchMoveToStadium,
  DraftRoundPhaseOpenMarketCardSelection,
  DraftRoundPhaseClashCardSelectionForOpponent,
  DraftRoundPhaseDiscardCardOverflow,
  PlayoffRoundSetupPhase,
  PlayoffRoundPhaseTeamReveal,
  PlayoffRoundPhaseMainMatch,
  PlayoffRoundPhaseInterMatchAddPlayers,
  PlayoffRoundPhaseInterMatchDiscardPlayers,
  PlayoffRoundPhaseTieMatch,
  PlayoffRoundPhaseScore
}
