export enum LocationType {
  ArenaDeckSpot,
  ArenaDiscardSpot,
  CurrentArenasRowSpot,
  BusStationBoardSpot,
  BusTokenSpotBelowBusStationBoard,
  HockeyPlayerDeckSpot,
  HockeyPlayerDraftSpot,
  HockeyPlayerOpenMarketDraftLocator,
  PlayerBusTokenReserveSpot,
  PlayerBusTokenTeamSpot,
  PlayerHockeyPlayerHandSpot,
  PlayerHockeyPlayerTeamSpot,
  PlayerPlayoffTicketTokenSpot,
  PlayoffPointCardSpot,
  TieBreakerCardSpot,
  PlayerReminderSpot,
  BusSpotOnArenaCardLadder
}
